### ISSUE TITLE
Have to log in again after export

### ISSUE THREAD

**Issue by broizter** [vwxyzjn/portwarden#19] opened 2019-01-04 20:14 UTC
Having some issues trying to automate this tool without using the webui. I wanna be able to export with the CLI tool daily from a cron script. The first snag I have is that it logs me out completely from BitWarden CLI after every export. The second is that there is no way to pass the --session argument from BitWarden CLI to Portwarden to utilize an already unlocked vault. This snag I can work around though so my biggest issue is the logout problem.

**Comment by vwxyzjn** [comment] 2019-01-05 16:16
Hi Niklas,

Thanks for trying out portwarden. In regards to the logout issue, that was the intended behavior. Portwarden server handles multiple users by logging out the Bitwarden CLI every time an export is performed since Bitwarden CLI does not allow multiple accounts logged in at the same time.

However, I do see your use case. Perhaps I could add a command line argument such as —no-logout?

Costa


________________________________

**Comment by broizter** [comment] 2019-01-05 18:02
Adding an argument that will prevent the logout would be fantastic! Hope it's not too much trouble.

**Comment by vwxyzjn** [comment] 2019-01-10 05:39
This should be fixed by PR #18, could you download the suitable binary from the following list and give it a try?

[portwarden_darwin_amd64.zip](https://github.com/vwxyzjn/portwarden/files/2743726/portwarden_darwin_amd64.zip)
[Uploading portwarden_linux_amd64.zip…]()
[Uploading portwarden_windows_amd64.zip…]()

**Comment by broizter** [comment] 2019-01-10 11:51
It works perfectly, thank you very much!

**Closed** 2019-01-16 21:34 UTC
